version: "3.9"
services:
  db:
    ports:
      - "5432:5432"
      # - "127.0.0.1:5432:5432"
    image: postgres:latest
    environment:
      POSTGRES_USER: "db_admin_user"
      POSTGRES_DB: "movierama"
      POSTGRES_PASSWORD: "password123"
  web-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "db"
        # entrypoint: ["diesel setup", "/app/target/release/movie-rama"]

